version: "3.8"

services:
    db: 
        container_name: ensolvers_sap_db
        image: postgres:13
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: ensolvers_sap
        restart: always

    prod:
        container_name: ensolvers_sap_prod
        image: ensolvers-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
            - 9229:9229
        restart: unless-stopped
        depends_on:
          - db
        environment:
          - DB_HOST=db
          - DB_PORT=5432
          - DB_NAME=ensolvers_sap
          - DB_USER=admin
          - DB_PASS=admin123