version: '3.3'

services:
    db: 
        container_name: ensolvers_sap_db
        image: postgres:13
        ports:
            - 8080:8080
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: ensolvers_sap
        restart: always

    dev:
        container_name: ensolvers_sap_dev
        image: ensolvers-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
          - db

    prod:
        container_name: ensolvers_sap_prod
        image: ensolvers-api-prod:1.0.0
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
          - db
